Write-Host "IRAS client binaries are built by GitHub Actions."
Write-Host ""
Write-Host "After pushing this repository to GitHub:"
Write-Host "  Actions -> Build Windows EXE -> Run workflow"
Write-Host "  Actions -> Build Android APK -> Run workflow"
Write-Host ""
Write-Host "Artifacts:"
Write-Host "  IRAS-Windows-EXE / IRAS.exe"
Write-Host "  IRAS-Android-APK / app-debug.apk"
