param(
    [string]$ServerUrl = "",
    [ValidateSet("read_only", "control", "full")]
    [string]$Mode = "full",
    [switch]$AllowPower,
    [switch]$AllowCommand,
    [switch]$FullFileSystem,
    [string[]]$AllowedRoot = @(),
    [switch]$NoStartupTask
)

$ErrorActionPreference = "Stop"
$TaskName = "IRAS Remote Windows Agent"

function Test-IRASPlaceholderUrl {
    param([string]$Url)
    $value = if ($null -eq $Url) { "" } else { [string]$Url }
    $value = $value.Trim().ToLowerInvariant()
    if (-not $value) { return $true }
    return (
        $value.Contains("your-iras-cloud") -or
        $value.Contains("your-server") -or
        $value.Contains("<your") -or
        $value.EndsWith(".example") -or
        $value.Contains("example.invalid") -or
        $value.Contains("example.com")
    )
}

if (-not $ServerUrl) {
    $ServerUrl = Read-Host "IRAS Cloud HTTPS URL (for example https://iras-cloud-abc1.onrender.com)"
}
$ServerUrl = $ServerUrl.Trim().TrimEnd('/')

if (Test-IRASPlaceholderUrl $ServerUrl) {
    throw "ServerUrl is still a placeholder. Deploy IRAS Cloud first, then pass its real HTTPS URL (for example https://iras-cloud-abc1.onrender.com)."
}

if (-not ($ServerUrl.StartsWith("https://") -or $ServerUrl.StartsWith("http://127.0.0.1") -or $ServerUrl.StartsWith("http://localhost"))) {
    throw "Remote IRAS requires HTTPS. localhost is allowed only for testing."
}

# Fail before asking for a secret when the cloud endpoint itself is not usable.
# Render free services can cold-start slowly, so allow a bounded 30-second probe.
try {
    $health = Invoke-RestMethod -Uri ($ServerUrl + "/health") -Method Get -TimeoutSec 30
    if ($null -eq $health -or $health.ok -ne $true) {
        throw "The server answered /health but did not report ok=true."
    }
    $cloudVersion = [string]$health.version
    if ([string]::IsNullOrWhiteSpace($cloudVersion) -or $cloudVersion -notmatch '^4\.') {
        throw "IRAS Cloud is reachable but is not running the v4 remote backend (reported version: '$cloudVersion'). Deploy the current v4 code before pairing this laptop."
    }
} catch {
    throw "IRAS Cloud is not reachable at $ServerUrl/health. Deploy/start the cloud service and verify the real HTTPS URL before pairing this laptop. $($_.Exception.Message)"
}

$secureToken = Read-Host "IRAS_API_TOKEN (paste the 32+ character token generated by .\generate-iras-token.ps1)" -AsSecureString
$ptr = [Runtime.InteropServices.Marshal]::SecureStringToBSTR($secureToken)
try {
    $plainToken = [Runtime.InteropServices.Marshal]::PtrToStringBSTR($ptr)
} finally {
    [Runtime.InteropServices.Marshal]::ZeroFreeBSTR($ptr)
}

if ([string]::IsNullOrWhiteSpace($plainToken) -or $plainToken.Length -lt 32) {
    throw "IRAS_API_TOKEN is too short for remote administration. Generate one with .\generate-iras-token.ps1 and use the exact same value in the cloud service."
}
$uniqueChars = @($plainToken.ToCharArray() | Select-Object -Unique).Count
if ($uniqueChars -lt 12) {
    throw "IRAS_API_TOKEN failed the randomness sanity check. Generate a new token with .\generate-iras-token.ps1."
}

$pythonExe = (Get-Command python -ErrorAction Stop).Source
$deviceCommand = Get-Command iras-device -ErrorAction SilentlyContinue
$irasCommand = Get-Command iras -ErrorAction SilentlyContinue

# v4 may be extracted over an existing editable IRAS install. In that case the
# new `iras-device` console-script entry point may not exist until pip refreshes
# metadata, even though the module itself is already present. Fall back to
# `python -m iras.device_bridge.agent` so remote setup is self-healing instead
# of failing solely because the wrapper command is stale/missing.
$deviceExe = if ($deviceCommand) { $deviceCommand.Source } else { $pythonExe }
$devicePrefixArgs = if ($deviceCommand) { @() } else { @("-m", "iras.device_bridge.agent") }
$irasExe = if ($irasCommand) { $irasCommand.Source } else { $pythonExe }
$irasPrefixArgs = if ($irasCommand) { @() } else { @("-m", "iras.cli") }

$oldServer = $env:IRAS_SERVER_URL
$oldToken = $env:IRAS_API_TOKEN
try {
    $env:IRAS_SERVER_URL = $ServerUrl
    $env:IRAS_API_TOKEN = $plainToken
    $configureArgs = @("--configure", "--server-url", $ServerUrl)
    if ($FullFileSystem) {
        $roots = @("C:\")
        if (Test-Path "D:\") { $roots += "D:\" }
        foreach ($root in $roots) { $configureArgs += @("--allowed-root", $root) }
    } elseif ($AllowedRoot.Count -gt 0) {
        foreach ($root in $AllowedRoot) { $configureArgs += @("--allowed-root", $root) }
    }
    & $deviceExe @devicePrefixArgs @configureArgs
    if ($LASTEXITCODE -ne 0) { throw "IRAS device bridge configuration failed." }
} finally {
    $env:IRAS_SERVER_URL = $oldServer
    $env:IRAS_API_TOKEN = $oldToken
    $plainToken = $null
}

$armArgs = @("--remote-arm", $Mode, "--remote-persistent")
if ($AllowPower) { $armArgs += "--remote-allow-power" }
if ($AllowCommand) { $armArgs += "--remote-allow-shell" }
& $irasExe @irasPrefixArgs @armArgs
if ($LASTEXITCODE -ne 0) { throw "Failed to arm IRAS remote policy." }

if (-not $NoStartupTask) {
    if ($devicePrefixArgs.Count -gt 0) {
        $taskArgument = '-m iras.device_bridge.agent'
        $action = New-ScheduledTaskAction -Execute $deviceExe -Argument $taskArgument
    } else {
        $action = New-ScheduledTaskAction -Execute $deviceExe
    }
    $trigger = New-ScheduledTaskTrigger -AtLogOn -User $env:USERNAME
    $settings = New-ScheduledTaskSettingsSet -StartWhenAvailable -AllowStartIfOnBatteries -DontStopIfGoingOnBatteries -MultipleInstances IgnoreNew -ExecutionTimeLimit (New-TimeSpan -Days 3650) -RestartCount 10 -RestartInterval (New-TimeSpan -Minutes 1)
    $principal = New-ScheduledTaskPrincipal -UserId $env:USERNAME -LogonType Interactive -RunLevel Limited
    Register-ScheduledTask -TaskName $TaskName -Action $action -Trigger $trigger -Settings $settings -Principal $principal -Description "IRAS outbound-only authenticated remote Windows bridge" -Force | Out-Null
    Start-ScheduledTask -TaskName $TaskName
}

Write-Host ""
Write-Host "IRAS remote Windows access configured." -ForegroundColor Green
Write-Host "Server: $ServerUrl"
Write-Host "Local policy mode: $Mode"
Write-Host "Scheduled task: $(-not $NoStartupTask)"
Write-Host "Full filesystem roots: $FullFileSystem"
Write-Host "No inbound Windows port was opened. The laptop connects outbound to IRAS Cloud."
Write-Host "Remote-only stop: iras --remote-disarm"
Write-Host "Controller emergency stop: iras --emergency-stop"
Write-Host "For 24/7 reachability, configure Windows sleep separately; this script does not weaken lock/UAC/security settings."
Write-Host ""
Write-Host "Next check: iras --doctor"
